
class FormatIterator:
    def __init__(self, fmt):
        self.fmt = list(fmt)
    def next(self):
        s = ""
        if not self.fmt:
            raise StopIteration
        c = self.fmt.pop(0)
        while c == "x":
            if not self.fmt:
                raise StopIteration
            c = self.fmt.pop(0)
        hasnum = False
        while c.isdigit():
            hasnum = True
            s += c
            c = self.fmt.pop(0)
        if hasnum:
            if c != 's':
                num = int(s)
                newfmt = []
                for i in range(num):
                    newfmt.append(c)
                newfmt.extend(self.fmt)
                self.fmt = newfmt
                return self.fmt.pop(0)
        s += c
        return s
    def __iter__(self):
        return self

dexfmt = {}
dexfmt["diamond"] = ["BBBBBBBBBBHHHBBBBBBBBBBxx13s", 
    ["basehp"],
    ["baseatk"],
    ["basedef"],
    ["basespeed"],
    ["basespatk"],
    ["basespdef"],
    ["type1"],
    ["type2"],
    ["catchrate"],
    ["baseexp"],
    ["evs"],
    ["item1"],
    ["item2"],
    ["gender"],
    ["hatchcycle"],
    ["basehappy"],
    ["exprate"],
    ["egggroup1"],
    ["egggroup2"],
    ["ability1"],
    ["ability2"],
    ["flee"],
    ["color"],
    ["tms"]
]
dexfmt["platinum"] = dexfmt["diamond"][:]
dexfmt["heartgold"] = dexfmt["diamond"][:]
dexfmt["black"] = ["BBBBBBBBBBHHHHBBBBBBBBBBHHBBHHH", 
    ["basehp"],
    ["baseatk"],
    ["basedef"],
    ["basespeed"],
    ["basespatk"],
    ["basespdef"],
    ["type1"],
    ["type2"],
    ["catchrate"],
    ["stage"],
    ["evs"],
    ["item1"],
    ["item2"],
    ["item3"],
    ["gender"],
    ["hatchcycle"],
    ["basehappy"],
    ["exprate"],
    ["egggroup1"],
    ["egggroup2"],
    ["ability1"],
    ["ability2"],
    ["ability3"],
    ["flee"],
    ["formid"],
    ["form"],
    ["numforms"],
    ["color"],
    ["baseexp"],
    ["height"],
    ["weight"]
]
dexfmt["black2"] = dexfmt["black"][:]

evofmt = {}
evofmt["diamond"] = ["HHHHHHHHHHHHHHHHHHHHHxx",
    ["method1"],
    ["param1"],
    ["target1"],
    ["method2"],
    ["param2"],
    ["target2"],
    ["method3"],
    ["param3"],
    ["target3"],
    ["method4"],
    ["param4"],
    ["target4"],
    ["method5"],
    ["param5"],
    ["target5"],
    ["method6"],
    ["param6"],
    ["target6"],
    ["method7"],
    ["param7"],
    ["target7"],
]
evofmt["platinum"] = evofmt["diamond"][:]
evofmt["heartgold"] = evofmt["diamond"][:]
evofmt["black"] = evofmt["diamond"][:]
evofmt["black"][0] = "HHHHHHHHHHHHHHHHHHHHH"
evofmt["black2"] = evofmt["black"][:]

movefmt = {}
movefmt["diamond"] = ["H",
    ["moveid", 0, 8, 0x1FF],
    ["level", 9, 15, 0x7F],
]
movefmt["platinum"] = movefmt["diamond"][:]
movefmt["heartgold"] = movefmt["diamond"][:]
movefmt["black"] = ["I",
    ["moveid", 0, 15, 0xFFFF],
    ["level", 16, 31, 0xFFFF],
]
movefmt["black2"] = movefmt["black"][:]

movedatafmt = {}
movedatafmt["diamond"] = ["HBBBBBBHbBBBxx",
    ["effect"],
    ["category"],
    ["power"],
    ["type"],
    ["accuracy"],
    ["pp"],
    ["effectchance"],
    ["flag1"],
    ["priority"],
    ["flag2"],
    ["contesteffect"],
    ["contesttype"]
]
movedatafmt["platinum"] = movedatafmt["diamond"][:]
movedatafmt["heartgold"] = movedatafmt["diamond"][:]
movedatafmt["black"] = ["BBBBBBbBhBBBBBBHBBBBBBBBBBBBxxHxx",
    ["type"],
    ["effectcategory"],
    ["category"],
    ["power"],
    ["accuracy"],
    ["pp"],
    ["priority"],
    ["hits"],
    ["resulteffect"],
    ["effectchance"],
    ["status"],
    ["minturns"],
    ["maxturns"],
    ["crit"],
    ["flinch"],
    ["effect"],
    ["recoil"],
    ["healing"],
    ["target"],
    ["stat1"],
    ["stat2"],
    ["stat3"],
    ["magnitude1"],
    ["magnitude2"],
    ["magnitude3"],
    ["statchance1"],
    ["statchance2"],
    ["statchance3"],
    ["flag"]
]
movedatafmt["black2"] = movedatafmt["black"][:]

trdatafmt = {}
trdatafmt["diamond"] = ["BBBBHHHHIBxxx",
    ["flag"],
    ["class"],
    ["battletype"],
    ["numpokemon"],
    ["item1"],
    ["item2"],
    ["item3"],
    ["item4"],
    ["ai"],
    ["battletype2"],
]
trdatafmt["platinum"] = trdatafmt["diamond"][:]
trdatafmt["heartgold"] = trdatafmt["diamond"][:] # TODO: may need fixing
trdatafmt["black"] = trdatafmt["diamond"][:] # TODO: may need fixing
trdatafmt["black2"] = trdatafmt["black"][:]

itemdatafmt = {}
itemdatafmt["diamond"] = ["H"+"B"*18+"b"*6+"BBbbb",
    ["price"],
    ["batteeffect"],
    ["gain"],
    ["berrytag"],
    ["flingeffect"],
    ["flingpower"],
    ["naturalpower"],
    ["flag1"],
    ["pocket"],
    ["itemtype"],
    ["itemcategory"],
    ["flag2"],
    ["flag3"],
    ["flag4"],
    ["flag5"],
    ["xstat1"],
    ["xstat2"],
    ["xstat3"],
    ["flag6"],
    ["hpev"],
    ["atkev"],
    ["defev"],
    ["speev"],
    ["spaev"],
    ["spdev"],
    ["hprestore"],
    ["pprestore"],
    ["happy1"],
    ["happy2"],
    ["happy3"],
]

encfmt = {}
encfmt["diamond"] = ["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"+"IIIIII"+"IIIIIIIII"+
    "IBBxxIBBxxIBBxxIBBxxIBBxxI"+"x"*44+"IBBxxIBBxxIBBxxIBBxxIBBxxI"*3,
    "rate",
    "level1",
    "natid1",
    "level2",
    "natid2",
    "level3",
    "natid3",
    "level4",
    "natid4",
    "level5",
    "natid5",
    "level6",
    "natid6",
    "level7",
    "natid7",
    "level8",
    "natid8",
    "level9",
    "natid9",
    "level10",
    "natid10",
    "level11",
    "natid11",
    "level12",
    "natid12",
    "morning1",
    "morning2",
    "day1",
    "day2",
    "night1",
    "night2",
    "radar1",
    "radar2",
    "radar3",
    "radar4",
    "unknown1",
    "unknown2",
    "unknown3",
    "unknown4",
    "unknown5",
    "unknown6",
    "ruby1",
    "ruby2",
    "sapphire1",
    "sapphire2",
    "emerald1",
    "emerald2",
    "red1",
    "red2",
    "green1",
    "green2",
    "surfrate",
    "surf1maxlevel",
    "surf1minlevel",
    "surf1natid",
    "surf2maxlevel",
    "surf2minlevel",
    "surf2natid",
    "surf3maxlevel",
    "surf3minlevel",
    "surf3natid",
    "surf4maxlevel",
    "surf4minlevel",
    "surf4natid",
    "surf5maxlevel",
    "surf5minlevel",
    "surf5natid",
    "oldrodrate",
    "oldrod1maxlevel",
    "oldrod1minlevel",
    "oldrod1natid",
    "oldrod2maxlevel",
    "oldrod2minlevel",
    "oldrod2natid",
    "oldrod3maxlevel",
    "oldrod3minlevel",
    "oldrod3natid",
    "oldrod4maxlevel",
    "oldrod4minlevel",
    "oldrod4natid",
    "oldrod5maxlevel",
    "oldrod5minlevel",
    "oldrod5natid",
    "goodrodrate",
    "goodrod1maxlevel",
    "goodrod1minlevel",
    "goodrod1natid",
    "goodrod2maxlevel",
    "goodrod2minlevel",
    "goodrod2natid",
    "goodrod3maxlevel",
    "goodrod3minlevel",
    "goodrod3natid",
    "goodrod4maxlevel",
    "goodrod4minlevel",
    "goodrod4natid",
    "goodrod5maxlevel",
    "goodrod5minlevel",
    "goodrod5natid",
    "superrodrate",
    "superrod1maxlevel",
    "superrod1minlevel",
    "superrod1natid",
    "superrod2maxlevel",
    "superrod2minlevel",
    "superrod2natid",
    "superrod3maxlevel",
    "superrod3minlevel",
    "superrod3natid",
    "superrod4maxlevel",
    "superrod4minlevel",
    "superrod4natid",
    "superrod5maxlevel",
    "superrod5minlevel",
    "superrod5natid",
]
encfmt["platinum"] = encfmt["diamond"][:]
encfmt["heartgold"] = ["BBBBBBxxBBBBBBBBBBBBHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
    +"BBH"*(5*4+2)+"HH",
    "walkrate",
    "surfrate",
    "rocksmashrate",
    "oldrodrate",
    "goodrodrate",
    "superrodrate",
    "walklevel1",
    "walklevel2",
    "walklevel3",
    "walklevel4",
    "walklevel5",
    "walklevel6",
    "walklevel7",
    "walklevel8",
    "walklevel9",
    "walklevel10",
    "walklevel11",
    "walklevel12",
    "walknatidmorning1",
    "walknatidmorning2",
    "walknatidmorning3",
    "walknatidmorning4",
    "walknatidmorning5",
    "walknatidmorning6",
    "walknatidmorning7",
    "walknatidmorning8",
    "walknatidmorning9",
    "walknatidmorning10",
    "walknatidmorning11",
    "walknatidmorning12",
    "walknatidday1",
    "walknatidday2",
    "walknatidday3",
    "walknatidday4",
    "walknatidday5",
    "walknatidday6",
    "walknatidday7",
    "walknatidday8",
    "walknatidday9",
    "walknatidday10",
    "walknatidday11",
    "walknatidday12",
    "walknatidnight1",
    "walknatidnight2",
    "walknatidnight3",
    "walknatidnight4",
    "walknatidnight5",
    "walknatidnight6",
    "walknatidnight7",
    "walknatidnight8",
    "walknatidnight9",
    "walknatidnight10",
    "walknatidnight11",
    "walknatidnight12",
    "hoennnatid1",
    "hoennnatid2",
    "sinnohnatid1",
    "sinnohnatid2",
    "surf1minlevel",
    "surf1maxlevel",
    "surf1natid",
    "surf2minlevel",
    "surf2maxlevel",
    "surf2natid",
    "surf3minlevel",
    "surf3maxlevel",
    "surf3natid",
    "surf4minlevel",
    "surf4maxlevel",
    "surf4natid",
    "surf5minlevel",
    "surf5maxlevel",
    "surf5natid",
    "rocksmash1minlevel",
    "rocksmash1maxlevel",
    "rocksmash1natid",
    "rocksmash2minlevel",
    "rocksmash2maxlevel",
    "rocksmash2natid",
    "oldrod1minlevel",
    "oldrod1maxlevel",
    "oldrod1natid",
    "oldrod2minlevel",
    "oldrod2maxlevel",
    "oldrod2natid",
    "oldrod3minlevel",
    "oldrod3maxlevel",
    "oldrod3natid",
    "oldrod4minlevel",
    "oldrod4maxlevel",
    "oldrod4natid",
    "oldrod5minlevel",
    "oldrod5maxlevel",
    "oldrod5natid",
    "goodrod1minlevel",
    "goodrod1maxlevel",
    "goodrod1natid",
    "goodrod2minlevel",
    "goodrod2maxlevel",
    "goodrod2natid",
    "goodrod3minlevel",
    "goodrod3maxlevel",
    "goodrod3natid",
    "goodrod4minlevel",
    "goodrod4maxlevel",
    "goodrod4natid",
    "goodrod5minlevel",
    "goodrod5maxlevel",
    "goodrod5natid",
    "superrod1minlevel",
    "superrod1maxlevel",
    "superrod1natid",
    "superrod2minlevel",
    "superrod2maxlevel",
    "superrod2natid",
    "superrod3minlevel",
    "superrod3maxlevel",
    "superrod3natid",
    "superrod4minlevel",
    "superrod4maxlevel",
    "superrod4natid",
    "superrod5minlevel",
    "superrod5maxlevel",
    "superrod5natid",
    "radionatid1",
    "radionatid2",
]

def sortentry(s):
    return [s, "H", ["natid"]]
searchfiles = {}
searchfiles["diamond"] = {
    0:["weight","I",["hg"]],
    1:["height","I",["dm"]],
    11:sortentry("national"),
    12:sortentry("regional"),
    13:sortentry("alphabetical"),
    14:sortentry("heaviest"),
    15:sortentry("lightest"),
    16:sortentry("tallest"),
    17:sortentry("smallest"),
    18:sortentry("ABC"),
    19:sortentry("DEF"),
    20:sortentry("GHI"),
    21:sortentry("JKL"),
    22:sortentry("MNO"),
    23:sortentry("PQR"),
    24:sortentry("STU"),
    25:sortentry("VWX"),
    26:sortentry("YZ"),
    27:sortentry("normal"),
    28:sortentry("fighting"),
    29:sortentry("flying"),
    30:sortentry("poison"),
    31:sortentry("ground"),
    32:sortentry("rock"),
    33:sortentry("bug"),
    34:sortentry("ghost"),
    35:sortentry("steel"),
    36:sortentry("fire"),
    37:sortentry("water"),
    38:sortentry("grass"),
    39:sortentry("electric"),
    40:sortentry("psychic"),
    41:sortentry("ice"),
    42:sortentry("dragon"),
    43:sortentry("dark"),
}
searchfiles["platinum"] = searchfiles["diamond"]
searchfiles["heartgold"] = {
    0:["weight","I",["hg"]],
    1:["height","I",["dm"]],
    11:sortentry("national"),
    12:sortentry("regional"),
    13:sortentry("alphabetical"),
    14:sortentry("heaviest"),
    15:sortentry("lightest"),
    16:sortentry("tallest"),
    17:sortentry("smallest"),
    93:sortentry("ABC"),
    94:sortentry("DEF"),
    95:sortentry("GHI"),
    96:sortentry("JKL"),
    97:sortentry("MNO"),
    98:sortentry("PQR"),
    99:sortentry("STU"),
    100:sortentry("VWX"),
    101:sortentry("YZ"),
    62:sortentry("normal"),
    63:sortentry("fighting"),
    64:sortentry("flying"),
    65:sortentry("poison"),
    66:sortentry("ground"),
    67:sortentry("rock"),
    68:sortentry("bug"),
    69:sortentry("ghost"),
    70:sortentry("steel"),
    71:sortentry("fire"),
    72:sortentry("water"),
    73:sortentry("grass"),
    74:sortentry("electric"),
    75:sortentry("psychic"),
    76:sortentry("ice"),
    77:sortentry("dragon"),
    78:sortentry("dark"),
}